pipeline {
  agent none
  stages {
    
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        
        sh '''
              echo '
                public class Hello {


                      public static void main(String[] args)
                    {

                            System.out.println("Hello world");
                      }
                 }

' >  Hello.java


#complie java code
javac Hello.java


#run java code
java Hello

     '''


                      
  
      }
    }

  
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}

