pipeline{
   agent any
    

  stages {

   stage('checkout code')
{

    step {
     
           git branch: 'main' ,url:'https://github.com/Devops-Scripting-practice/scripting.git'


}

    stage('check jdk')
{


	step
{
        sh 'java --version'



}
}

     stage('compile java program')
{

      step {

	sh 'javac Code1.java'
	sh 'java Code1'
 } 

 }
 }
 }
}
